'use strict';
const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
let paused = reduced.matches;
const asset = 'assets/';
const layers = [
['Dados & contexto','Dados que viram contexto.','Conecte fontes, estruture conhecimento e entregue contexto rastreável para a IA compreender o seu negócio.',['RAG','Bases vetoriais','Curadoria'],'data-viz.mp4'],
['Inteligência decisória','Decisões com mais inteligência.','Transforme dados relacionais e temporais em previsões, scores e recomendações para vendas, risco, operações e compras.',['Previsões','Recomendações','Anomalias'],'data-viz.mp4'],
['Sistemas agênticos','Agentes que trabalham juntos.','Orquestre agentes com estado, memória e rastreabilidade. Conecte pessoas e sistemas para executar processos dentro de limites definidos.',['Orquestração','Memória','Rastreabilidade'],'generative-ai.mp4'],
['AI Runtime','O modelo certo. A cada execução.','Direcione cada tarefa pelo equilíbrio entre qualidade, custo, latência e criticidade. Modelos externos são componentes modulares e substituíveis.',['Roteamento','Qualidade','Eficiência'],'futuristic-3d.mp4'],
['Treinamento & adaptação','Inteligência no seu contexto.','Adapte modelos ao domínio da empresa com curadoria, fine-tuning, versionamento e avaliação contínua.',['Fine-tuning','Versionamento','Avaliação'],'futuristic-3d.mp4'],
['Segurança & conformidade','Controle em todas as camadas.','Proteja dados sensíveis com anonimização, reconhecimento de entidades em português e trilhas de auditoria. Incorpore a LGPD à arquitetura.',['Privacidade','LGPD','Auditoria'],'biometric-auth.mp4'],
['AI Ops & observabilidade','Operação que evolui com você.','Acompanhe qualidade, custo, latência, drift e segurança. Avalie o comportamento da IA e evolua a operação com evidências.',['Observabilidade','Benchmarking','Avaliação'],'data-viz.mp4'],
['Execução & integração','Inteligência conectada à empresa.','Integre agentes e aplicações aos sistemas que já fazem parte da sua operação: APIs, ERP, CRM, workflows e sistemas legados.',['APIs','Conectores','Workflows'],'telecom.mp4']
];
const list=document.querySelector('.layer-list');
layers.forEach((l,i)=>{const b=document.createElement('button');b.className='layer-tab';b.id=`layer-${i}`;b.setAttribute('role','tab');b.setAttribute('aria-controls','layer-panel');b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${l[0]}<b>↗</b>`;b.addEventListener('click',()=>setLayer(i));b.addEventListener('keydown',e=>{let n=i;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%8;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+7)%8;else if(e.key==='Home')n=0;else if(e.key==='End')n=7;else return;e.preventDefault();setLayer(n);list.children[n].focus()});list.append(b)});
let currentLayer=-1;
function setLayer(i){if(i===currentLayer)return;currentLayer=i;const l=layers[i];[...list.children].forEach((b,n)=>{b.setAttribute('aria-selected',n===i);b.tabIndex=n===i?0:-1});document.querySelector('#layer-panel').setAttribute('aria-labelledby',`layer-${i}`);document.querySelector('#layer-count').textContent=`${String(i+1).padStart(2,'0')} / 08`;document.querySelector('#layer-title').textContent=l[1];document.querySelector('#layer-description').textContent=l[2];document.querySelector('#layer-tags').innerHTML=l[3].map(t=>`<span>${t}</span>`).join('');const v=document.querySelector('#layer-video');if(!v.src.endsWith(l[4])){v.pause();v.src=asset+l[4];v.load()}if(!paused&&v.getBoundingClientRect().top<innerHeight&&v.getBoundingClientRect().bottom>0)v.play().catch(()=>{})}
setLayer(0);
const caseSlugs=["automacao-de-vendas-no-whatsapp-com-agentes-de-ia", "ia-para-produtividade-e-precisao-em-prontuarios-medicos", "monitoramento-inteligente-de-obras-com-drones-e-visao-computacional", "precificacao-dinamica-inteligente", "analise-de-perfil-de-clientes-para-upsell-e-cross-sell-com-ia", "gestao-preditiva-de-frotas-e-inventario", "otimizacao-de-performance-no-surf-com-visao-computacional", "separacao-de-fotos-e-videos-por-reconhecimento-facial", "seguranca-digital-e-eficiencia-com-ia", "assessment-de-ia-para-otimizacao-de-processos-bancarios", "agente-de-ia-para-interpretacao-de-contas-razao", "analise-de-midia-sentimentos-e-relatorios-com-ia", "ia-que-transforma-dados-de-navegacao-em-otimizacoes-de-cx", "plataforma-b2b-para-canais-e-inteligencia-de-mercado", "qualificacao-de-leads-humano-digital-e-sumarizacao-de-rfp", "ia-para-extratos-ocupacao-cobrancas-vistorias-e-recibos", "prontuario-eletronico-com-dominio-de-terminologia-medica", "assistente-virtual-de-reservas-com-ia", "otimizacao-logistica-com-visao-computacional-em-armazem"];
const caseArtFiles=caseSlugs.map(s=>'case-'+s+(s==='separacao-de-fotos-e-videos-por-reconhecimento-facial'?'-v2':'')+'.jpg');
const cases=[
['Finanças','Automação de vendas no WhatsApp com agentes de IA','Fintech de saque antecipado de FGTS'],
['Saúde','IA para produtividade e precisão em prontuários médicos','Saúde / hospitalar'],
['Construção','Monitoramento inteligente de obras com drones e visão computacional','Monitoramento de canteiros de obras'],
['Hotelaria','Precificação dinâmica inteligente','Rede hoteleira econômica'],
['Finanças','Análise de perfil de clientes para upsell e cross-sell com IA','Private banking / alta renda'],
['Logística','Gestão preditiva de frotas e inventário','Logística para mineração, siderurgia, óleo e gás'],
['Esporte','Otimização de performance no surf com visão computacional','Escola de surf em piscina de ondas artificiais'],
['Esporte','Separação de fotos e vídeos por reconhecimento facial','Fotografia esportiva de surf'],
['Tecnologia','Segurança digital e eficiência com IA','IncentiveTech — fidelidade e recompensas'],
['Finanças','Assessment de IA para otimização de processos bancários','Consórcios de imóveis, veículos e bens duráveis'],
['Finanças','Agente de IA para interpretação de contas razão','Consultoria financeira / Orçamento Base Zero'],
['Comunicação','Análise de mídia, sentimentos e relatórios com IA','Comunicação e relações públicas'],
['Aviação','IA que transforma dados de navegação em otimizações de CX','Aviação comercial'],
['Tecnologia','Plataforma B2B para canais e inteligência de mercado','Fabricante de hardware e eletrônicos'],
['Saúde','Qualificação de leads, humano digital e sumarização de RFP','Produtos e serviços científicos para laboratórios, saúde e pesquisa'],
['Construção','IA para extratos, ocupação, cobranças, vistorias e recibos','Administração de imóveis'],
['Saúde','Prontuário eletrônico com domínio de terminologia médica','Saúde de excelência / medicina de precisão'],
['Hotelaria','Assistente virtual de reservas com IA','Hospitalidade / rede de hotéis'],
['Varejo','Otimização logística com visão computacional em armazém','Marketplace / e-commerce / serviços financeiros']
];
let filter='Todos',expanded=false;
const filters=document.querySelector('.case-filters'),grid=document.querySelector('.case-grid'),more=document.querySelector('.more-cases'),dialog=document.querySelector('#case-dialog');
['Todos',...new Set(cases.map(c=>c[0]))].forEach(s=>{const b=document.createElement('button');b.className='filter';b.textContent=s;b.setAttribute('aria-pressed',s==='Todos');b.addEventListener('click',()=>{filter=s;expanded=false;renderCases()});filters.append(b)});
function renderCases(){[...filters.children].forEach(b=>b.setAttribute('aria-pressed',b.textContent===filter));const selected=cases.filter(c=>filter==='Todos'||c[0]===filter);grid.replaceChildren();(expanded?selected:selected.slice(0,5)).forEach(c=>{const b=document.createElement('a');b.href='cases/'+caseSlugs[cases.indexOf(c)]+'/';b.className='case-card';b.innerHTML=`<img class="card-art" src="assets/illustrations/${caseArtFiles[cases.indexOf(c)]}" alt="${c[1]} — ilustração conceitual" width="1536" height="1024" loading="lazy" decoding="async"><span class="case-sector">${c[0]}</span><h3>${c[1]}</h3><span class="case-client">${c[2]}</span><span class="case-arrow" aria-hidden="true">↗</span>`;grid.append(b)});more.hidden=selected.length<=5;more.style.display=selected.length<=5?'none':'inline-flex';more.innerHTML=expanded?'Mostrar seleção de cases ↑':`Explorar todos os ${selected.length} cases <span>↗</span>`}
more.addEventListener('click',()=>{expanded=!expanded;renderCases();window.ScrollTrigger?.refresh()});renderCases();
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const pillars=[['Identidade & acesso','SSO, segregação de ambientes, perfis e permissões para definir quem pode acessar e executar cada ação.'],['Proteção de dados','Anonimização, pseudonimização, retenção e proteção de dados sensíveis, com reconhecimento de entidades em português.'],['Limites de autonomia','Guardrails, validações e supervisão humana mantêm a atuação dos agentes dentro das políticas autorizadas.'],['Auditoria & rastreabilidade','Registro de fontes, decisões, versões, modelos e interações para demonstrar como a IA operou.'],['Segurança de IA','Controles contra prompt injection, vazamento de informações e uso indevido de ferramentas.'],['Conformidade','LGPD, políticas internas e prestação de contas incorporadas ao desenho da operação.']];
document.querySelector('.security-list').innerHTML=pillars.map((p,i)=>`<details ${i===0?'open':''}><summary>${p[0]}</summary><p>${p[1]}</p></details>`).join('');
const steps=[['AI Mapping','Mapeamos dores, dados, riscos e oportunidades.'],['Business Design','Desenhamos a experiência, o fluxo e os indicadores.'],['Data & Context','Conectamos, preparamos e governamos os dados.'],['Build & Integrate','Construímos agentes, aplicações e integrações.'],['Deploy & Validate','Validamos qualidade, segurança e desempenho.'],['Operate & Scale','Monitoramos, evoluímos e expandimos a operação.']];
const methodArtIds=["method-ai-mapping", "method-business-design", "method-data-context", "method-build-integrate", "method-deploy-validate", "method-operate-scale"];
document.querySelector('.method-grid').innerHTML=steps.map((s,i)=>`<article><img class="method-card-art" src="assets/illustrations/${methodArtIds[i]}.jpg" alt="${s[0]} — ilustração conceitual" width="1536" height="1024" loading="lazy" decoding="async"><span>0${i+1}</span><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('');
const nav=document.querySelector('#nav'),menu=document.querySelector('.menu-toggle'),mega=document.querySelector('#mega'),trigger=document.querySelector('.nav-trigger');
function closeMenus(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');if(mega)mega.hidden=true;trigger?.setAttribute('aria-expanded','false')}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});trigger?.addEventListener('click',()=>{if(innerWidth<=900){closeMenus();document.querySelector('#plataforma').scrollIntoView({behavior:paused?'instant':'smooth'});return}mega.hidden=!mega.hidden;trigger.setAttribute('aria-expanded',!mega.hidden)});
document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenus()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const hadMenu=(mega&&!mega.hidden)||nav.classList.contains('open');closeMenus();if(hadMenu)(innerWidth<=900?menu:(trigger||menu)).focus()}});
document.querySelectorAll('.header a').forEach(a=>a.addEventListener('click',()=>{if(a.dataset.layer)setLayer(Number(a.dataset.layer));closeMenus()}));
const videos=[...document.querySelectorAll('.observed-video')];const visibility=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{target.dataset.visible=String(isIntersecting);if(isIntersecting&&!paused)target.play().catch(()=>{});else target.pause()}),{threshold:.12});videos.forEach(v=>visibility.observe(v));
const motionButton=document.querySelector('.motion-toggle');function updateMotion(){document.body.classList.toggle('motion-paused',paused);motionButton.setAttribute('aria-pressed',paused);motionButton.setAttribute('aria-label',paused?'Retomar vídeos':'Pausar vídeos');motionButton.textContent=paused?'▷':'Ⅱ';videos.forEach(v=>{if(paused)v.pause();else if(v.dataset.visible==='true')v.play().catch(()=>{})});}
motionButton.addEventListener('click',()=>{paused=!paused;updateMotion()});reduced.addEventListener('change',()=>{paused=reduced.matches;updateMotion()});updateMotion();
if(window.gsap&&window.ScrollTrigger&&!reduced.matches){gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(min-width: 901px)',()=>{const text=document.querySelector('.reveal-words');text.innerHTML=text.innerHTML.split(/(<br>)/).map(part=>part==='<br>'?part:part.split(' ').map(w=>w?`<span class="word">${w}</span>`:'').join(' ')).join('');gsap.fromTo('.word',{opacity:.18},{opacity:1,stagger:.2,ease:'none',scrollTrigger:{trigger:'.narrative',start:'top top',end:'+=700',pin:'.narrative-stage',scrub:.5}});gsap.fromTo('.layer-art img',{y:60,scale:.9},{y:-20,scale:1,ease:'none',scrollTrigger:{trigger:'.architecture',start:'top bottom',end:'bottom top',scrub:1}})});gsap.from('.hero-content>*',{y:25,opacity:0,duration:1,stagger:.15,ease:'power2.out'});window.addEventListener('load',()=>ScrollTrigger.refresh(),{once:true});}
